# These are supported funding model platforms

We accept Cryptocurrency in the form of Monero Only at this time.

477myk6hAgZEHdFp3NFUtd9CGkUSzN9mcieBJvyq2hJUDFvcrHAyNZ1LVLv9UgMXHTbp2GxtvzfTpFCcqddNa95G9ZVKGS8


